// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package net

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register("net", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Pure: true,
	Native: []*pkg.Builtin{{
		Name:      "SplitHostPort",
		Signature: "func(s: string) -> [string, string]",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.ListKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret, c.Err = SplitHostPort(s)
			}
		},
	}, {
		Name:      "JoinHostPort",
		Signature: "func(host: string | bytes | [...int], port: string | bytes | int) -> string",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.TopKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			host, port := c.Value(0), c.Value(1)
			if c.Do() {
				c.Ret, c.Err = JoinHostPort(host, port)
			}
		},
	}, {
		Name:      "FQDN",
		Signature: "func(s: string) -> bool",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = FQDN(s)
			}
		},
	}, {
		Name:  "IPv4len",
		Const: "4",
	}, {
		Name:  "IPv6len",
		Const: "16",
	}, {
		Name:      "ParseIP",
		Signature: "func(s: string) -> ([int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255] | [int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255])",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.ListKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret, c.Err = ParseIP(s)
			}
		},
	}, {
		Name:      "IPv4",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = IPv4(ip)
			}
		},
	}, {
		Name:      "IPv6",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = IPv6(ip)
			}
		},
	}, {
		Name:      "IP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = IP(ip)
			}
		},
	}, {
		Name:      "IPCIDR",
		Signature: "func(ip: string | bytes) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = IPCIDR(ip)
			}
		},
	}, {
		Name:      "LoopbackIP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = LoopbackIP(ip)
			}
		},
	}, {
		Name:      "MulticastIP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = MulticastIP(ip)
			}
		},
	}, {
		Name:      "InterfaceLocalMulticastIP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = InterfaceLocalMulticastIP(ip)
			}
		},
	}, {
		Name:      "LinkLocalMulticastIP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = LinkLocalMulticastIP(ip)
			}
		},
	}, {
		Name:      "LinkLocalUnicastIP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = LinkLocalUnicastIP(ip)
			}
		},
	}, {
		Name:      "GlobalUnicastIP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = GlobalUnicastIP(ip)
			}
		},
	}, {
		Name:      "UnspecifiedIP",
		Signature: "func(ip: string | bytes | [...int]) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = UnspecifiedIP(ip)
			}
		},
	}, {
		Name:      "ToIP4",
		Signature: "func(ip: string | bytes | [...int]) -> [int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255]",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.ListKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = ToIP4(ip)
			}
		},
	}, {
		Name:      "ToIP16",
		Signature: "func(ip: string | bytes | [...int]) -> [int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255, int & >=0 & <=255]",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.ListKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = ToIP16(ip)
			}
		},
	}, {
		Name:      "IPString",
		Signature: "func(ip: string | bytes | [...int]) -> string",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			ip := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = IPString(ip)
			}
		},
	}, {
		Name:      "AddIP",
		Signature: "func(ip: string | bytes | [...int], offset: int) -> string",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.IntKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			ip, offset := c.Value(0), c.BigInt(1)
			if c.Do() {
				c.Ret, c.Err = AddIP(ip, offset)
			}
		},
	}, {
		Name:      "AddIPCIDR",
		Signature: "func(ip: string | bytes, offset: int) -> string",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.IntKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			ip, offset := c.Value(0), c.BigInt(1)
			if c.Do() {
				c.Ret, c.Err = AddIPCIDR(ip, offset)
			}
		},
	}, {
		Name:      "ParseCIDR",
		Signature: "func(s: string) -> {prefix_mask: string, prefix_len: int & >=0 & <=128, prefix_addr: string, broadcast_addr?: string}",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StructKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret, c.Err = ParseCIDR(s)
			}
		},
	}, {
		Name:      "InCIDR",
		Signature: "func(ip: string | bytes | [...int], cidr: string | bytes) -> bool",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.TopKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			ip, cidr := c.Value(0), c.Value(1)
			if c.Do() {
				c.Ret, c.Err = InCIDR(ip, cidr)
			}
		},
	}, {
		Name:      "CompareIP",
		Signature: "func(ip1: string | bytes | [...int], ip2: string | bytes | [...int]) -> -1 | 0 | 1",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.TopKind},
		},
		Result: adt.IntKind,
		Func: func(c *pkg.CallCtxt) {
			ip1, ip2 := c.Value(0), c.Value(1)
			if c.Do() {
				c.Ret, c.Err = CompareIP(ip1, ip2)
			}
		},
	}, {
		Name: "PathEscape",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = PathEscape(s)
			}
		},
	}, {
		Name: "PathUnescape",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret, c.Err = PathUnescape(s)
			}
		},
	}, {
		Name: "QueryEscape",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = QueryEscape(s)
			}
		},
	}, {
		Name: "QueryUnescape",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret, c.Err = QueryUnescape(s)
			}
		},
	}, {
		Name:      "URL",
		Signature: "func(s: string) -> bool",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret, c.Err = URL(s)
			}
		},
	}, {
		Name:      "AbsURL",
		Signature: "func(s: string) -> bool",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret, c.Err = AbsURL(s)
			}
		},
	}},
	CUE: `
@experiment(functions)
@pure()
SplitHostPort: func(s: string) -> [...]
JoinHostPort:  func(host: _, port: _) -> string
ParseIP:       func(s: string) -> [...]
ToIP4:         func(ip: _) -> [...]
ToIP16:        func(ip: _) -> [...]
IPString:      func(ip: _) -> string
AddIP:         func(ip: _, offset: int) -> string
AddIPCIDR:     func(ip: _, offset: int) -> string
ParseCIDR:     func(s: string) -> {...}
InCIDR:        func(ip: _, cidr: _) -> bool
CompareIP:     func(ip1: _, ip2: _) -> int
PathEscape:    func(s: string) -> string
PathUnescape:  func(s: string) -> string
QueryEscape:   func(s: string) -> string
QueryUnescape: func(s: string) -> string
#IP:           string | bytes | [...int]
#CIDR:         string | bytes`,
}
