// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package tabwriter

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register("text/tabwriter", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Pure: true,
	Native: []*pkg.Builtin{{
		Name:      "Write",
		Signature: "func(data: string | bytes | [...(string | bytes)]) -> string",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			data := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = Write(data)
			}
		},
	}},
	CUE: `
@experiment(functions)
@pure()
Write: func(data: _) -> string`,
}
