// Copyright 2018 The CUE Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build ignore

// gen.go generates the pkg.go files inside the packages under the pkg
// directory. The pkg.cue definition files alongside them are
// maintained by hand; their consistency with the registered builtins
// is checked by the tests of the pkg package.
//
// Be sure to also update an entry in pkg/pkg.go, if so desired.
package main

import (
	"bytes"
	"cmp"
	_ "embed"
	"flag"
	"fmt"
	goast "go/ast"
	"go/constant"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"math/big"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"

	"cuelang.org/go/cue/ast"
	cueformat "cuelang.org/go/cue/format"
	"cuelang.org/go/cue/parser"
)

const pkgParent = "cuelang.org/go/pkg"

func main() {
	flag.Parse()
	log.SetFlags(log.Lshortfile)
	log.SetOutput(os.Stdout)

	cfg := &packages.Config{Mode: packages.NeedName | packages.NeedFiles | packages.NeedTypes | packages.NeedSyntax}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		fmt.Fprintf(os.Stderr, "load: %v\n", err)
		os.Exit(1)
	}
	// Errors in the root pkg package are tolerated: it embeds the
	// generated pkg.cue files, so it cannot load in a tree where they
	// have not yet been generated, and nothing is generated from it.
	errCount := 0
	for _, pkg := range pkgs {
		if pkg.PkgPath == pkgParent {
			continue
		}
		for _, err := range pkg.Errors {
			fmt.Fprintln(os.Stderr, err)
			errCount++
		}
	}
	if errCount > 0 {
		os.Exit(1)
	}
	if err := checkNativeMetadata(pkgs); err != nil {
		log.Fatal(err)
	}
	// Sort the Go packages by import path; otherwise adding a new builtin package
	// puts it at the very end of the list the first time it is getting added to register.go,
	// as it's not imported by the root package yet. Sorting ensures consistent output.
	slices.SortFunc(pkgs, func(a, b *packages.Package) int {
		return cmp.Compare(a.PkgPath, b.PkgPath)
	})

	regBuf := new(bytes.Buffer)
	fmt.Fprintf(regBuf, "// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(regBuf, "package pkg\n\n")
	fmt.Fprintf(regBuf, "import (\n")
	for _, pkg := range pkgs {
		switch {
		case pkg.PkgPath == pkgParent:
			// The pkg package itself should not be generated.
		case strings.Contains(pkg.PkgPath, "/internal"):
			// Internal packages are not for public use.
		default:
			fmt.Fprintf(regBuf, "\t_ %q\n", pkg.PkgPath)
			if err := generate(pkg); err != nil {
				log.Fatalf("%s: %v", pkg, err)
			}
		}
	}
	fmt.Fprintf(regBuf, ")\n")
	if err := os.WriteFile("register.go", regBuf.Bytes(), 0o666); err != nil {
		log.Fatal(err)
	}
}

// An emitter accumulates one generated file for a standard library
// package. The package's members are reported to it in source order,
// followed by the package's supplemental CUE file, if it has one.
type emitter interface {
	// constant records an exported constant and its rendered value.
	constant(obj *types.Const, value string)

	// function records an exported function usable as a builtin.
	function(fn *types.Func)

	// supplementalCUE records the package's supplemental CUE files,
	// maintained alongside its Go sources, as the file-level attributes
	// they declare followed by their declarations. It is reported after
	// the members, so that an emitter can first take from it whatever a
	// member's own declaration needs.
	supplementalCUE(file *ast.File) error

	// close formats the accumulated file and writes it to the
	// package's directory.
	close() error
}

// emitters broadcasts each call to every emitter in the list.
type emitters []emitter

func (es emitters) constant(obj *types.Const, value string) {
	for _, e := range es {
		e.constant(obj, value)
	}
}

func (es emitters) function(fn *types.Func) {
	for _, e := range es {
		e.function(fn)
	}
}

func (es emitters) supplementalCUE(file *ast.File) error {
	for _, e := range es {
		if err := e.supplementalCUE(file); err != nil {
			return err
		}
	}
	return nil
}

func (es emitters) close() error {
	for _, e := range es {
		if err := e.close(); err != nil {
			return err
		}
	}
	return nil
}

// generate writes the generated pkg.go file for a package.
func generate(pkg *packages.Package) error {
	// go/packages supports multiple build systems, including some which don't keep
	// a Go package entirely within a single directory.
	// However, we know for certain that CUE uses modules, so it is the case here.
	// We can figure out the directory from the first Go file.
	pkgDir := filepath.Dir(pkg.GoFiles[0])
	cuePkg := strings.TrimPrefix(pkg.PkgPath, pkgParent+"/")

	params := headerParams{
		GoPkg:  pkg.Name,
		CUEPkg: cuePkg,
	}
	// As a special case, the "tool" package cannot be imported from CUE.
	skipRegister := params.CUEPkg == "tool"
	if skipRegister {
		params.CUEPkg = ""
	}

	if doc, err := os.ReadFile(filepath.Join(pkgDir, "doc.txt")); err == nil {
		defs, err := os.ReadFile(filepath.Join(pkgDir, pkg.Name+".cue"))
		if err != nil {
			return err
		}
		i := bytes.Index(defs, []byte("package "+pkg.Name))
		defs = defs[i+len("package "+pkg.Name)+1:]
		defs = bytes.TrimRight(defs, "\n")
		defs = bytes.ReplaceAll(defs, []byte("\n"), []byte("\n//\t"))
		params.PackageDoc = string(doc)
		params.PackageDefs = string(defs)
	}

	sup, err := loadSupplementalCUE(pkgDir)
	if err != nil {
		return fmt.Errorf("error processing %s: %v", cuePkg, err)
	}
	pure := purePackage(pkg)

	var emits emitters
	// TODO remove this special case. Currently the path pkg.go file
	// cannot be generated automatically but that will be possible when
	// we can attach arbitrary signatures to builtin functions. The CUE
	// definition file is generated like any other package's.
	if pkg.PkgPath != "cuelang.org/go/pkg/path" {
		goEmit, err := newGoEmitter(pkgDir, pkg.PkgPath, params, !skipRegister, pure)
		if err != nil {
			return err
		}
		emits = append(emits, goEmit)
	}
	if !skipRegister {
		emitMembers(pkg, cuePkg, emits)

		if sup != nil {
			if err := emits.supplementalCUE(sup); err != nil {
				return err
			}
		}
	}
	return emits.close()
}

var (
	typeError = types.Universe.Lookup("error").Type()
	typeByte  = types.Universe.Lookup("byte").Type()
)

// validatorType is the type of the result by which a builtin declares
// that it is intended for use as a validator; see
// [cuelang.org/go/internal/pkg.Validator]. It aliases bool.
const validatorType = "cuelang.org/go/internal/pkg.Validator"

// experimentFunctions is the file-level attribute admitting the
// function-type syntax the definition files are written in.
const experimentFunctions = "@experiment(functions)"

// purePackage reports whether the package's hand-written Go sources
// carry the //cue:pure directive: the claim, judged and recorded by
// the package's author, that every builtin in the package is pure.
// The generator turns it into the @pure() attribute of the package's
// definition file and runtime CUE.
func purePackage(pkg *packages.Package) bool {
	for _, f := range pkg.Syntax {
		if goast.IsGenerated(f) {
			continue
		}
		for _, cg := range f.Comments {
			for _, c := range cg.List {
				if c.Text == "//cue:pure" {
					return true
				}
			}
		}
	}
	return false
}

// emitMembers feeds the package's exported constants and functions,
// in source order, to the emitter.
func emitMembers(pkg *packages.Package, cuePkgPath string, e emitter) {
	// We sort the objects by their original source code position.
	// Otherwise, go/types defaults to sorting by name strings.
	// We could remove this code if we were fine with sorting by name.
	scope := pkg.Types.Scope()
	type objWithPos struct {
		obj types.Object
		pos token.Position
	}
	var objs []objWithPos
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		objs = append(objs, objWithPos{obj, pkg.Fset.Position(obj.Pos())})
	}
	slices.SortFunc(objs, func(a, b objWithPos) int {
		if c := cmp.Compare(a.pos.Filename, b.pos.Filename); c != 0 {
			return c
		}
		return cmp.Compare(a.pos.Line, b.pos.Line)
	})

	for _, obj := range objs {
		obj := obj.obj // no longer need the token.Position
		if !obj.Exported() {
			continue
		}
		// TODO: support type declarations.
		switch obj := obj.(type) {
		case *types.Const:
			var value string
			switch v := obj.Val(); v.Kind() {
			case constant.Bool, constant.Int, constant.String:
				// TODO: convert octal numbers
				value = v.ExactString()
			case constant.Float:
				var rat big.Rat
				rat.SetString(v.ExactString())
				var float big.Float
				float.SetRat(&rat)
				value = float.Text('g', -1)
			default:
				fmt.Printf("Dropped entry %s.%s (%T: %v)\n", cuePkgPath, obj.Name(), v.Kind(), v.ExactString())
				continue
			}
			e.constant(obj, value)
		case *types.Func:
			sign := obj.Signature()
			if sign.Recv() != nil {
				continue
			}
			results := sign.Results()
			if results == nil || (results.Len() != 1 && results.At(1).Type() != typeError) {
				fmt.Printf("Dropped func %s.%s: must have one return value or a value and an error %v\n", cuePkgPath, obj.Name(), sign)
				continue
			}
			e.function(obj)
		}
	}
}

// loadSupplementalCUE parses the directory's supplemental CUE files and
// returns their combined contents as a file: the file-level attributes the
// sources declare, followed by every file's declarations. The files form one
// CUE package, so their declarations are concatenated in sorted filename
// order, which keeps the generated output stable.
// If the directory has no such file, it returns (nil, nil).
//
// The result is a file rather than a bare expression because file-level
// attributes such as @experiment(functions) have no other place to live, and
// both the formatter here and [pkg.Package.MustCompile] must see them to
// accept the syntax they enable. The package clause and any imports are
// dropped: the blob is unified into the package vertex, which supplies the
// name, and imports have never been supported here.
//
// Comments are kept, as the declarations are re-emitted individually
// into the definition file rather than copied as a block of source.
//
// It avoids the cue/load and cuecontext packages because they depend
// on the standard library which is what this command is generating -
// cyclic dependencies are undesirable in general.
func loadSupplementalCUE(dir string) (*ast.File, error) {
	cuefiles, err := filepath.Glob(filepath.Join(dir, "*.cue"))
	if err != nil {
		return nil, err
	}
	// The generated pkg.cue file is this generator's output, never
	// its input.
	cuefiles = slices.DeleteFunc(cuefiles, func(name string) bool {
		return filepath.Base(name) == "pkg.cue"
	})
	if len(cuefiles) == 0 {
		return nil, nil
	}
	slices.Sort(cuefiles)

	var attrs, decls []ast.Decl
	seenAttr := map[string]bool{}
	for _, name := range cuefiles {
		b, err := os.ReadFile(name)
		if err != nil {
			return nil, err
		}
		file, err := parser.ParseFile(name, b, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		preamble := file.Preamble()
		if len(preamble) == 0 {
			return nil, fmt.Errorf("no package clause in %s", name)
		}
		for _, d := range preamble {
			// Hoist file-level attributes, deduplicating those that several
			// files declare; drop the package clause and imports.
			a, ok := d.(*ast.Attribute)
			if !ok || seenAttr[a.Text] {
				continue
			}
			seenAttr[a.Text] = true
			attrs = append(attrs, &ast.Attribute{Text: a.Text})
		}
		decls = append(decls, file.Decls[len(preamble):]...)
	}
	if len(decls) == 0 {
		return nil, nil
	}
	return &ast.File{Decls: append(attrs, decls...)}, nil
}

type headerParams struct {
	GoPkg  string
	CUEPkg string

	PackageDoc  string
	PackageDefs string
}

var header = template.Must(template.New("").Parse(
	`// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

{{if .PackageDoc}}
{{.PackageDoc -}}
//     {{.PackageDefs}}
{{end -}}
package {{.GoPkg}}

{{if .CUEPkg -}}
import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register({{printf "%q" .CUEPkg}}, p)
}

var _ = adt.TopKind // in case the adt package isn't used
{{end}}
`))

// A goEmitter generates a package's pkg.go file, which registers the
// package's builtins with the runtime.
type goEmitter struct {
	dir     string
	pkgPath string
	// registered is whether the package registers itself for import
	// from CUE; the "tool" package does not, and its pkg.go holds only
	// the file header.
	registered bool
	// pure is whether the package's Go sources carry the //cue:pure
	// directive, the claim that every builtin in the package is pure.
	pure bool

	w *bytes.Buffer
	// sigs accumulates the derived signature declarations, which the
	// CUE blob carries so that each declaration unifies with the
	// builtin it describes when the package is compiled.
	sigs *bytes.Buffer
	// supAttrs and supDecls hold the package's supplemental CUE: its
	// file-level attributes and the rendered declarations.
	supAttrs    []string
	supDecls    string
	first       bool
	nonConcrete bool
}

func newGoEmitter(dir, pkgPath string, params headerParams, registered, pure bool) (*goEmitter, error) {
	g := &goEmitter{
		dir:        dir,
		pkgPath:    pkgPath,
		registered: registered,
		pure:       pure,
		w:          &bytes.Buffer{},
		sigs:       &bytes.Buffer{},
		first:      true,
	}
	if err := header.Execute(g.w, params); err != nil {
		return nil, err
	}
	if registered {
		fmt.Fprintf(g.w, "var p = &pkg.Package{\n")
		if pure {
			fmt.Fprintln(g.w, "Pure: true,")
		}
		fmt.Fprint(g.w, "Native: []*pkg.Builtin{")
	}
	return g, nil
}

func (g *goEmitter) sep() {
	if g.first {
		g.first = false
		return
	}
	fmt.Fprint(g.w, ", ")
}

func (g *goEmitter) constant(obj *types.Const, value string) {
	g.sep()
	fmt.Fprintf(g.w, "{\nName: %q,\n Const: %q,\n}", obj.Name(), value)
}

// function emits a function's builtin implementation, and its derived
// signature for the package's CUE blob. The blob carries the call form
// alone: the validator constructor saves the trailing native arguments and
// derives its domain from the validated slot. A bare
// validator gets no blob signature at all — its kind is that of the
// value it validates rather than func, so no function type can unify
// with it.
func (g *goEmitter) function(fn *types.Func) {
	if !bareValidator(fn) {
		fmt.Fprintf(g.sigs, "%s: %s\n", fn.Name(), deriveCallForm(fn, false))
	}

	g.nonConcrete = false
	sign := fn.Signature()
	params := sign.Params()
	results := sign.Results()

	g.sep()
	fmt.Fprintf(g.w, "{\n")
	defer fmt.Fprintf(g.w, "}")

	fmt.Fprintf(g.w, "Name: %q,\n", fn.Name())
	if precise := deriveCallForm(fn, true); precise != deriveCallForm(fn, false) {
		fmt.Fprintf(g.w, "Signature: %q,\n", precise)
	}
	if refinements := nativeRefinements[strings.TrimPrefix(fn.Pkg().Path(), pkgParent+"/")+"."+fn.Name()]; len(refinements) != 0 {
		fmt.Fprintf(g.w, "Refinements: %#v,\n", refinements)
	}

	needCallContext := false
	args := []string{}
	vals := []string{}
	kind := []string{}
	for param := range params.Variables() {
		typ := param.Type()
		if typ.String() == "cuelang.org/go/internal/pkg.Schema" {
			needCallContext = true
		}
		methodName := g.callCtxtGetter(typ)
		argKind := g.adtKind(param.Type())
		vals = append(vals, fmt.Sprintf("c.%s(%d)", methodName, len(args)))
		args = append(args, param.Name())
		kind = append(kind, argKind)
	}

	fmt.Fprintf(g.w, "Params: []pkg.Param{\n")
	for _, k := range kind {
		fmt.Fprintf(g.w, "{Kind: %s},\n", k)
	}
	fmt.Fprintf(g.w, "\n},\n")

	fmt.Fprintf(g.w, "Result: %s,\n", g.adtResultKind(results.At(0).Type()))
	if g.nonConcrete {
		fmt.Fprintf(g.w, "NonConcrete: true,\n")
	}

	argList := strings.Join(args, ", ")
	valList := strings.Join(vals, ", ")
	init := ""
	if len(args) > 0 {
		init = fmt.Sprintf("%s := %s", argList, valList)
	}

	name := fn.Name()
	if needCallContext {
		argList = "c.OpContext(), " + argList

		// Main function is used for Godoc documentation. Once we have proper
		// CUE function signatures, we can remove these stubs.
		// NOTE: this will not work for scripts that are not cased. But this
		// is intended to be a temporary situation anyway.
		name = strings.ToLower(name[:1]) + name[1:]
	}

	fmt.Fprintf(g.w, "Func: func(c *pkg.CallCtxt) {")
	defer fmt.Fprintln(g.w, "},")
	fmt.Fprintln(g.w)
	if init != "" {
		fmt.Fprintln(g.w, init)
	}
	fmt.Fprintln(g.w, "if c.Do() {")
	defer fmt.Fprintln(g.w, "}")
	if results.Len() == 1 && results.At(0).Type() == typeError {
		fmt.Fprintf(g.w, "c.Ret, c.Err = true, %s(%s)", name, argList)
	} else if results.Len() == 1 {
		fmt.Fprintf(g.w, "c.Ret = %s(%s)", name, argList)
	} else {
		fmt.Fprintf(g.w, "c.Ret, c.Err = %s(%s)", name, argList)
	}
}

// supplementalCUE records the supplemental declarations for the
// package's CUE field, which the runtime mixes in with the native
// builtins.
func (g *goEmitter) supplementalCUE(file *ast.File) error {
	var decls []ast.Decl
	for _, d := range file.Decls {
		if a, ok := d.(*ast.Attribute); ok {
			g.supAttrs = append(g.supAttrs, a.Text)
			continue
		}
		decls = append(decls, d)
	}

	b, err := cueformat.Node(&ast.File{Decls: decls})
	if err != nil {
		return err
	}
	g.supDecls = string(b)
	return nil
}

// cueBlob renders the package's CUE field: the file-level attributes,
// the derived signature declarations, and the supplemental
// declarations. Each signature unifies with the builtin of the same
// name when the package is compiled, tightening it and rejecting a
// derivation that contradicts the registration.
func (g *goEmitter) cueBlob() (string, error) {
	var src bytes.Buffer
	if g.sigs.Len() > 0 {
		src.WriteString(experimentFunctions + "\n")
	}
	if g.pure {
		src.WriteString("@pure()\n")
	}
	for _, a := range g.supAttrs {
		if a != experimentFunctions && a != "@pure()" {
			src.WriteString(a + "\n")
		}
	}
	src.Write(g.sigs.Bytes())
	src.WriteString(g.supDecls)
	if src.Len() == 0 {
		return "", nil
	}

	// The blob is data the binary carries at run time, so the comments
	// the sources are parsed with are dropped: they are for the
	// definition file, which is written for people to read.
	stripped, err := parser.ParseFile(g.pkgPath, src.Bytes())
	if err != nil {
		return "", err
	}
	b, err := cueformat.Node(stripped)
	if err != nil {
		return "", err
	}

	// Compact the CUE by removing empty lines. This requires re-formatting to align fields.
	// TODO(mvdan): provide a "compact" option in cue/format for this purpose?
	b = bytes.ReplaceAll(b, []byte("\n\n"), []byte("\n"))
	b, err = cueformat.Source(b)
	if err != nil {
		return "", err
	}
	b = bytes.TrimSpace(b) // no trailing newline

	// Try to use a Go string with backquotes, for readability. The string
	// opens with a newline so that every top-level declaration, including
	// the first, starts at the same column in the generated source.
	// If not possible due to cueSrc itself having backquotes,
	// use a single-line double-quoted string, removing tabs for brevity.
	// We don't use strconv.CanBackquote as it is for quoting as a single line.
	if cueSrc := string(b); !strings.Contains(cueSrc, "`") {
		return fmt.Sprintf("CUE: `\n%s`,\n", cueSrc), nil
	}
	cueSrc := strings.ReplaceAll(string(b), "\t", "")
	return fmt.Sprintf("CUE: %q,\n", cueSrc), nil
}

// close formats the accumulated Go source and writes it to pkg.go in
// the package's directory.
func (g *goEmitter) close() error {
	if g.registered {
		fmt.Fprintf(g.w, "},\n")
		blob, err := g.cueBlob()
		if err != nil {
			return err
		}
		g.w.WriteString(blob)
		fmt.Fprintf(g.w, "}\n")
	}
	b, err := format.Source(g.w.Bytes())
	if err != nil {
		fmt.Printf("go/format error on %s: %v\n", g.pkgPath, err)
		b = g.w.Bytes() // write the unformatted source
	}
	return os.WriteFile(filepath.Join(g.dir, "pkg.go"), b, 0o666)
}

// callCtxtGetter returns the name of the [cuelang.org/go/internal/pkg.CallCtxt] method
// which can be used to fetch a parameter of the given type.
func (g *goEmitter) callCtxtGetter(typ types.Type) string {
	switch typ := typ.(type) {
	case *types.Basic:
		return strings.Title(typ.String()) // "int" turns into "Int"
	case *types.Slice:
		switch typ.Elem().String() {
		case "byte":
			return "Bytes"
		case "string":
			return "StringList"
		case "*cuelang.org/go/internal.Decimal":
			return "DecimalList"
		}
		return "List"
	}
	switch typ.String() {
	case "*math/big.Int":
		return "BigInt"
	case "*math/big.Float":
		return "BigFloat"
	case "*cuelang.org/go/internal.Decimal":
		return "Decimal"
	case "cuelang.org/go/internal/pkg.List":
		return "CueList"
	case "cuelang.org/go/internal/pkg.Struct":
		return "Struct"
	case "cuelang.org/go/cue.Value",
		"cuelang.org/go/cue/ast.Expr":
		return "Value"
	case "cuelang.org/go/internal/pkg.Schema":
		g.nonConcrete = true
		return "Schema"
	case "io.Reader":
		return "Reader"
	}
	log.Fatal("callCtxtGetter: unhandled Go type ", typ.String())
	return ""
}

// adtResultKind provides a Go expression string which describes a
// [cuelang.org/go/internal/core/adt.Kind] value for a builtin's
// result. It differs from a parameter's kind for a Go []byte: as an
// argument that also accepts a string, which the builtin converts, but
// as a result it is always bytes — nothing converts it back. A lone error
// result reports successful validation as a Boolean.
func (g *goEmitter) adtResultKind(typ types.Type) string {
	if typ == typeError {
		return "adt.BoolKind"
	}
	if isByteSlice(typ) {
		return "adt.BytesKind"
	}
	return g.adtKind(typ)
}

// adtKind provides a Go expression string which describes
// a [cuelang.org/go/internal/core/adt.Kind] value for the given type,
// as accepted for a parameter. See [goEmitter.adtResultKind] for a
// result.
func (g *goEmitter) adtKind(typ types.Type) string {
	// TODO: detect list and structs types for return values.
	switch typ := typ.(type) {
	case *types.Slice:
		if typ.Elem() == typeByte {
			return "adt.BytesKind | adt.StringKind"
		}
		return "adt.ListKind"
	case *types.Map:
		return "adt.StructKind"
	case *types.Basic:
		if typ.Info()&types.IsInteger != 0 {
			return "adt.IntKind"
		}
		if typ.Kind() == types.Float64 {
			return "adt.NumberKind"
		}
		return "adt." + strings.Title(typ.String()) + "Kind" // "bool" turns into "adt.BoolKind"
	}
	switch typ.String() {
	case "error":
		return "adt.BottomKind"
	case validatorType:
		return "adt.BoolKind"
	case "io.Reader":
		return "adt.BytesKind | adt.StringKind"
	case "cuelang.org/go/internal/pkg.Struct":
		return "adt.StructKind"
	case "cuelang.org/go/internal/pkg.List":
		return "adt.ListKind"
	case "*math/big.Int":
		return "adt.IntKind"
	case "*cuelang.org/go/internal.Decimal", "*math/big.Float":
		return "adt.NumberKind"
	case "cuelang.org/go/cue.Value", "cuelang.org/go/cue/ast.Expr", "cuelang.org/go/internal/pkg.Schema":
		return "adt.TopKind" // TODO: can be more precise

	// Some builtin functions return custom types, like [cuelang.org/go/pkg/time.Split].
	// TODO: we can simplify this once the CUE API declarations in ./pkg/...
	// use CUE function signatures to validate their parameters and results.
	case "*cuelang.org/go/pkg/time.Parts":
		return "adt.StructKind"
	case "*cuelang.org/go/pkg/net.ParsedCIDR":
		return "adt.StructKind"
	}
	log.Fatal("adtKind: unhandled Go type ", typ.String())
	return ""
}

// deriveCallForm returns a native signature. The runtime blob retains its
// existing kind constraints; precise checking metadata additionally preserves
// Go container elements and converted record fields. Parameter names match the
// native slots in both forms. Authored definitions may state further refinements
// not expressible in Go signatures.
func deriveCallForm(fn *types.Func, precise bool) string {
	if precise {
		if signature := nativeSignatures[nativeName(fn)]; signature != "" {
			return signature
		}
	}
	sign := fn.Signature()
	params := sign.Params()
	defParams := make([]string, params.Len())
	for i := range defParams {
		defParams[i] = defParam(fn, params.At(i), precise)
	}
	result := cueKindResultType(sign.Results().At(0).Type())
	if precise {
		result = cueResultType(sign.Results().At(0).Type())
		if refined := nativeResults[nativeName(fn)]; refined != "" {
			result = refined
		}
	}
	return fmt.Sprintf("func(%s) -> %s", strings.Join(defParams, ", "), result)
}

// These contracts express relationships erased by Go's []cue.Value API.
// They are checking evidence only; runtime argument completion is unchanged.
var nativeSignatures = map[string]string{
	"list.Drop":        "forall(A) func(x: [...A], n: int) -> [...A]",
	"list.Repeat":      "forall(A) func(x: [...A], count: int) -> [...A]",
	"list.Concat":      "forall(A) func(a: [...[...A]]) -> [...A]",
	"list.Take":        "forall(A) func(x: [...A], n: int) -> [...A]",
	"list.Slice":       "forall(A) func(x: [...A], i: int, j: int) -> [...A]",
	"list.Reverse":     "forall(A) func(x: [...A]) -> [...A]",
	"list.Max":         "forall(A: number) func(xs: [...A]) -> A",
	"list.Min":         "forall(A: number) func(xs: [...A]) -> A",
	"list.Sort":        "forall(A) func(list: [...A], cmp: {x: _, y: _, less: bool}) -> [...A]",
	"list.SortStable":  "forall(A) func(list: [...A], cmp: {x: _, y: _, less: bool}) -> [...A]",
	"list.SortStrings": "forall(A: string) func(a: [...A]) -> [...A]",
}

func nativeName(fn *types.Func) string {
	return strings.TrimPrefix(fn.Pkg().Path(), pkgParent+"/") + "." + fn.Name()
}

// A renamed native or argument must not silently drop a checking contract.
// Verify metadata against the loaded Go declarations before writing files.
func checkNativeMetadata(pkgs []*packages.Package) error {
	functions := make(map[string]*types.Func)
	for _, p := range pkgs {
		if p.Types == nil {
			continue
		}
		for _, name := range p.Types.Scope().Names() {
			if fn, ok := p.Types.Scope().Lookup(name).(*types.Func); ok && fn.Exported() {
				functions[nativeName(fn)] = fn
			}
		}
	}
	names := make(map[string]bool)
	for name := range nativeSignatures {
		names[name] = true
	}
	for name := range nativeResults {
		names[name] = true
	}
	for name := range nativeRefinements {
		names[name] = true
	}
	for name := range nativeParams {
		names[name] = true
	}
	for name := range names {
		fn := functions[name]
		if fn == nil {
			return fmt.Errorf("checking metadata refers to unknown native %s", name)
		}
		for label := range nativeParams[name] {
			found := false
			for param := range fn.Signature().Params().Variables() {
				found = found || param.Name() == label
			}
			if !found {
				return fmt.Errorf("checking metadata for %s refers to unknown parameter %s", name, label)
			}
		}
	}
	return nil
}

// Implementation facts that Go's representation types cannot express. Input
// descriptions retain ordinary partial-call domains; result descriptions
// describe every successful return, including edge cases such as underflow.
var nativeResults = map[string]string{
	"encoding/json.Unmarshal":       "null | bool | number | string | [...] | {...}",
	"encoding/yaml.Unmarshal":       "null | bool | number | string | bytes | [...] | {...}",
	"encoding/json.UnmarshalStream": "[...]",
	"encoding/yaml.UnmarshalStream": "[...]",
	"encoding/toml.Unmarshal":       "{...}",
	"math.Abs":                      "number & >=0",
	"math.Acosh":                    "number & >=0",
	"math.Acos":                     "number & >=0",
	"math.Cosh":                     "number & >=1",
	"math.Dim":                      "number & >=0",
	"math.Erf":                      "number & >=-1 & <=1",
	"math.Erfc":                     "number & >=0 & <=2",
	"math.Exp":                      "number & >=0",
	"math.Exp2":                     "number & >=0",
	"math.Expm1":                    "number & >=-1",
	"math.Hypot":                    "number & >=0",
	"math.Pow10":                    "number & >=0",
	"math.Cos":                      "number & >=-1 & <=1",
	"math.Sin":                      "number & >=-1 & <=1",
	"math.Sqrt":                     "number & >=0",
	"math.Tanh":                     "number & >=-1 & <=1",
	"math.Jacobi":                   "-1 | 0 | 1",
	"math/bits.At":                  "0 | 1",
	"math/bits.OnesCount":           "int & >=0",
	"math/bits.Len":                 "int & >=0",
	"strings.ByteAt":                "int & >=0 & <=255",
	"strings.Runes":                 "[...(int & >=0 & <=0x10ffff)]",
	"strings.Compare":               "-1 | 0 | 1",
	"strings.Count":                 "int & >=0",
	"strings.Index":                 "int & >=-1",
	"strings.LastIndex":             "int & >=-1",
	"strings.IndexAny":              "int & >=-1",
	"strings.LastIndexAny":          "int & >=-1",
	"strconv.ParseUint":             "int & >=0",
	"net.SplitHostPort":             "[string, string]",
	"net.CompareIP":                 "-1 | 0 | 1",
	"net.ParseIP":                   "(" + nativeTuple("int & >=0 & <=255", 4) + " | " + nativeTuple("int & >=0 & <=255", 16) + ")",
	"net.ToIP4":                     nativeTuple("int & >=0 & <=255", 4),
	"net.ToIP16":                    nativeTuple("int & >=0 & <=255", 16),
	"net.ParseCIDR":                 "{prefix_mask: string, prefix_len: int & >=0 & <=128, prefix_addr: string, broadcast_addr?: string}",
	"time.Split":                    "{year: int, month: int & >=1 & <=12, day: int & >=1 & <=31, hour: int & >=0 & <=23, minute: int & >=0 & <=59, second: int & >=0 & <=59, nanosecond: int & >=0 & <1000000000}",
	"uuid.ToInt":                    "int & >=0",
	"uuid.Variant":                  "int & >=0 & <=4",
	"uuid.Version":                  "int & >=0 & <=15",
}

func nativeTuple(element string, length int) string {
	return "[" + strings.TrimSuffix(strings.Repeat(element+", ", length), ", ") + "]"
}

var nativeParams = map[string]map[string]string{
	"encoding/json.Marshal":          {"v": "null | bool | number | string | bytes | [...] | {...}"},
	"encoding/yaml.Marshal":          {"v": "null | bool | number | string | bytes | [...] | {...}"},
	"encoding/openapi.MarshalSchema": {"config": "{version: string, selfContained?: bool, expandReferences?: bool, info?: _}"},
	"encoding/csv.Encode":            {"x": "[...[..._]]"},
	"encoding/json.MarshalStream":    {"v": "[...]"},
	"encoding/yaml.MarshalStream":    {"v": "[...]"},
	"encoding/toml.Marshal":          {"v": "{...}"},
	"list.IsSorted":                  {"cmp": "{x: _, y: _, less: bool}"},
	"list.FlattenN":                  {"xs": "[...]"},
	"net.JoinHostPort":               {"host": "string | bytes | [...int]", "port": "string | bytes | int"},
	"net.IPv4":                       {"ip": "string | bytes | [...int]"},
	"net.IPv6":                       {"ip": "string | bytes | [...int]"},
	"net.IP":                         {"ip": "string | bytes | [...int]"},
	"net.IPCIDR":                     {"ip": "string | bytes"},
	"net.LoopbackIP":                 {"ip": "string | bytes | [...int]"},
	"net.MulticastIP":                {"ip": "string | bytes | [...int]"},
	"net.InterfaceLocalMulticastIP":  {"ip": "string | bytes | [...int]"},
	"net.LinkLocalMulticastIP":       {"ip": "string | bytes | [...int]"},
	"net.LinkLocalUnicastIP":         {"ip": "string | bytes | [...int]"},
	"net.GlobalUnicastIP":            {"ip": "string | bytes | [...int]"},
	"net.UnspecifiedIP":              {"ip": "string | bytes | [...int]"},
	"net.ToIP4":                      {"ip": "string | bytes | [...int]"},
	"net.ToIP16":                     {"ip": "string | bytes | [...int]"},
	"net.IPString":                   {"ip": "string | bytes | [...int]"},
	"net.AddIP":                      {"ip": "string | bytes | [...int]"},
	"net.AddIPCIDR":                  {"ip": "string | bytes"},
	"net.InCIDR":                     {"ip": "string | bytes | [...int]", "cidr": "string | bytes"},
	"net.CompareIP":                  {"ip1": "string | bytes | [...int]", "ip2": "string | bytes | [...int]"},
	"strconv.FormatFloat":            {"fmtVal": "string | int"},
	"text/tabwriter.Write":           {"data": "string | bytes | [...(string | bytes)]"},
}

// Refinements add conditional evidence without shrinking the primary domain.
var nativeRefinements = map[string][]string{
	"math.Abs":     {"func(x: int) -> (int & >=0)"},
	"list.Sum":     {"func(xs: [...int]) -> int"},
	"list.Product": {"func(xs: [...int]) -> int"},
	"list.Range":   {"func(start: int, limit: int, step: int) -> [...int]"},
}

// bareValidator reports whether the builtin registers as a bare
// validator: a single parameter with a boolean result — a plain bool,
// a Validator, or an error alone, whose successful result is true. The
// evaluator wraps such a builtin at registration, so its kind is that
// of the value it validates rather than func.
func bareValidator(fn *types.Func) bool {
	sign := fn.Signature()
	if sign.Params().Len() != 1 {
		return false
	}
	result := sign.Results().At(0).Type()
	if result == typeError {
		return true
	}
	b, ok := result.Underlying().(*types.Basic)
	return ok && b.Kind() == types.Bool
}

// pathOSRequired lists the pkg/path builtins whose trailing OS
// parameter is required rather than optional with the "unix" default.
// It mirrors the hand-written pkg/path/pkg.go; drift between the two
// is caught by this directory's tests, which compare every sig
// attribute against the registered builtin's parameters.
var pathOSRequired = map[string]bool{
	"SplitList": true,
	"ToSlash":   true,
	"FromSlash": true,
}

// paramHasDefault reports whether a parameter carries a default when
// its function is called with fewer arguments.
func paramHasDefault(funcName string, param *types.Var) bool {
	return param.Type().String() == "cuelang.org/go/pkg/path.OS" &&
		!pathOSRequired[funcName]
}

// defParam returns the declaration of a function parameter for use in
// a signature. A plain named parameter is positional as well, so the
// name is the raw builtin slot's contract label and, through the attached
// function type, lets a labeled call select that slot. An unnamed Go parameter is
// rendered as its bare type. A parameter the builtin reads as a schema —
// typed pkg.Schema in Go, so deliberately accepting a non-concrete value —
// carries the @schema() attribute, which the definition files declare as
// well.
func defParam(fn *types.Func, param *types.Var, precise bool) string {
	name := param.Name()
	typ := cueKindType(param.Type())
	if precise {
		typ = cueType(param.Type())
		if refined := nativeParams[nativeName(fn)][name]; refined != "" {
			typ = refined
		}
	}
	switch param.Type().String() {
	case "cuelang.org/go/internal/pkg.Schema":
		typ += " @schema()"
	case "cuelang.org/go/pkg/path.OS":
		name = "os"
		if paramHasDefault(fn.Name(), param) {
			// A parameter default is declared with "=" after the
			// constraint; a default mark in the constraint is rejected.
			typ += ` = "unix"`
		}
	}
	if name == "" {
		return typ
	}
	return fmt.Sprintf("%s: %s", name, typ)
}

// cueResultType provides CUE syntax describing the value a builtin
// produces for the given Go result type. It differs from a parameter's
// type in two places.
//
// A Go []byte is bytes|string as an argument, which the builtin
// converts, but always bytes as a result: nothing converts it back.
//
// A Go result of error alone reports validation success as true.
// Non-nil errors remain failures rather than successful false results.
func cueResultType(typ types.Type) string {
	switch {
	case typ == typeError:
		return "true"
	case isByteSlice(typ):
		return "bytes"
	}
	switch t := typ.(type) {
	case *types.Basic:
		// Native integer results cannot exceed their Go representation.
		// Inputs keep the logical CUE int domain: representation failures
		// remain ordinary partial-call failures at the native boundary.
		width := 0
		switch t.Kind() {
		case types.Int8, types.Uint8:
			width = 8
		case types.Int16, types.Uint16:
			width = 16
		case types.Int32, types.Uint32:
			width = 32
		case types.Int, types.Int64, types.Uint, types.Uint64, types.Uintptr:
			width = 64
		}
		if width != 0 {
			max := new(big.Int).Lsh(big.NewInt(1), uint(width))
			if t.Info()&types.IsUnsigned != 0 {
				return "int & >=0 & <=" + max.Sub(max, big.NewInt(1)).String()
			}
			max.Rsh(max, 1)
			min := new(big.Int).Neg(max)
			return "int & >=" + min.String() + " & <=" + max.Sub(max, big.NewInt(1)).String()
		}
	case *types.Slice:
		return cueListType(cueResultType(t.Elem()))
	case *types.Map:
		return "{[string]: " + cueResultType(t.Elem()) + "}"
	}
	switch typ.String() {
	case "*cuelang.org/go/pkg/time.Parts", "*cuelang.org/go/pkg/net.ParsedCIDR":
		record := typ.(*types.Pointer).Elem().Underlying().(*types.Struct)
		var fields []string
		for i := range record.NumFields() {
			field := record.Field(i)
			if !field.Exported() {
				continue
			}
			tag := reflect.StructTag(record.Tag(i)).Get("json")
			name, options, _ := strings.Cut(tag, ",")
			if name == "-" {
				continue
			}
			if name == "" {
				name = field.Name()
			}
			presence := ""
			if slices.Contains(strings.Split(options, ","), "omitempty") {
				presence = "?"
			}
			fields = append(fields, fmt.Sprintf("%q%s: %s", name, presence, cueResultType(field.Type())))
		}
		return "{" + strings.Join(fields, ", ") + "}"
	}
	return cueType(typ)
}

func cueListType(element string) string {
	if element == "_" {
		return "[...]"
	}
	return "[..." + element + "]"
}

// isByteSlice reports whether typ is a Go []byte.
func isByteSlice(typ types.Type) bool {
	slice, ok := typ.(*types.Slice)
	return ok && slice.Elem() == typeByte
}

// cueKindType describes the kind accepted for a native Go parameter.
// cueType additionally retains container element types for checking.
func cueKindType(typ types.Type) string {
	switch typ := typ.(type) {
	case *types.Slice:
		if typ.Elem() == typeByte {
			return "bytes|string"
		}
		return "[...]"
	case *types.Map:
		return "{...}"
	case *types.Basic:
		if typ.Info()&types.IsInteger != 0 {
			return "int"
		}
		if typ.Kind() == types.Float64 {
			return "number"
		}
		return typ.String() // "bool" and "string" are CUE types too
	}
	switch typ.String() {
	case "error":
		return "_|_"
	case validatorType:
		return "bool"
	case "io.Reader":
		return "bytes|string"
	case "cuelang.org/go/internal/pkg.Struct":
		return "{...}"
	case "cuelang.org/go/internal/pkg.List":
		return "[...]"
	case "*math/big.Int":
		return "int"
	case "*cuelang.org/go/internal.Decimal", "*math/big.Float":
		return "number"
	case "cuelang.org/go/cue.Value",
		"cuelang.org/go/cue/ast.Expr",
		"cuelang.org/go/internal/pkg.Schema":
		return "_"
	case "cuelang.org/go/pkg/path.OS":
		return "string"

	// Some builtin functions return custom types, like [cuelang.org/go/pkg/time.Split].
	case "*cuelang.org/go/pkg/time.Parts":
		return "{...}"
	case "*cuelang.org/go/pkg/net.ParsedCIDR":
		return "{...}"
	}
	log.Fatal("cueType: unhandled Go type ", typ.String())
	return ""
}

// Keep runtime call constraints at their existing kind granularity. The
// precise signature is evidence for checking, not a source of argument values.
func cueKindResultType(typ types.Type) string {
	if typ == typeError {
		return "bool"
	}
	if isByteSlice(typ) {
		return "bytes"
	}
	return cueKindType(typ)
}

func cueType(typ types.Type) string {
	if t, ok := typ.(*types.Slice); ok && !isByteSlice(typ) {
		return cueListType(cueType(t.Elem()))
	}
	return cueKindType(typ)
}
